# version: "3.9"

services:
  db:
    image: postgres:15
    container_name: orchestrator-db
    environment:
      POSTGRES_DB: ${DB_NAME}  
      POSTGRES_USER: ${DB_USER}  
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  orchestrator:
    build: .
    container_name: orchestrator-app
    depends_on:
      db:
        condition: service_healthy
    env_file: 
      - .env  
    volumes:
      - ./Alerts:/app/Alerts
      - ./Orchestrator:/app/Orchestrator
      - ./api:/app/api 
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  postgres_data: